/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_7a;

import java.io.*;
import java.util.*;
import javax.swing.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author roel
 */
public class GUI extends javax.swing.JFrame {
    
    private BufferedReader inFile;
    static FileReader bestand;
    private String doorvoer;
    InvoerHandeler invoer = new InvoerHandeler();
    HashMap<String, String> readingFrames = new HashMap<String, String>();
    HashMap<String, String> aminozuurSequenties = new HashMap<String, String>();
    ArrayList<ORF> ORFs = new ArrayList<ORF>();
    
    public GUI() {
        initComponents();
        
    }
    
    public void openBestand() throws FileNotFoundException{
        File geselecteerdBestand;
        JFileChooser fileChooser;
        int reply;
        
        fileChooser = new JFileChooser();
        reply = fileChooser.showOpenDialog(this);
        if(reply == JFileChooser.APPROVE_OPTION){
            geselecteerdBestand = fileChooser.getSelectedFile();
            bestandsVeld.setText(geselecteerdBestand.getAbsolutePath());
            
        }
        
        bestand = new FileReader(bestandsVeld.getText());
        inFile = new BufferedReader(bestand);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bestandsVeld = new javax.swing.JTextField();
        bladerKnop = new javax.swing.JButton();
        openKnop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        analyzeKnop = new javax.swing.JButton();
        opslaanKnop = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bladerKnop.setText(" Bladeren");
        bladerKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bladerKnopActionPerformed(evt);
            }
        });

        openKnop.setText("Openen");
        openKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openKnopActionPerformed(evt);
            }
        });

        jLabel1.setText("Bestand:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("Sequentie:");

        analyzeKnop.setText("Analyze");
        analyzeKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzeKnopActionPerformed(evt);
            }
        });

        opslaanKnop.setText("Save to Database");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(analyzeKnop))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(bestandsVeld, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bladerKnop)
                        .addGap(38, 38, 38)
                        .addComponent(openKnop))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(640, 640, 640)
                .addComponent(opslaanKnop)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bladerKnop)
                    .addComponent(openKnop)
                    .addComponent(bestandsVeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(analyzeKnop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(150, 150, 150)
                .addComponent(opslaanKnop)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bladerKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bladerKnopActionPerformed
        try {
            openBestand();
        } catch (FileNotFoundException ex) {
           
        }
    }//GEN-LAST:event_bladerKnopActionPerformed

    private void openKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openKnopActionPerformed
        try {
            invoer.bestandLezen(inFile); 
            jTextArea1.setText(invoer.sequentie.toUpperCase());
            doorvoer = jTextArea1.getText();
     
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_openKnopActionPerformed

    private void analyzeKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeKnopActionPerformed
        boolean dna = invoer.DNAorNOT(doorvoer);
        if (!dna){
            System.out.println("geen dna");
            JOptionPane.showMessageDialog(null, "De sequentie die u wil analyzeren bevat corruptie");
        }
        else {
            readingFrames = new SequentieHandler().maakReadingFrames(doorvoer);
            aminozuurSequenties = new SequentieHandler().maakAminozuurSequentie(readingFrames);
            ORFs = new VoorspellenORF().voorspelORF(readingFrames);
            jLabel3.setText("Aantal ORFs: "+ORFs.size());
        }
        
    }//GEN-LAST:event_analyzeKnopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analyzeKnop;
    private javax.swing.JTextField bestandsVeld;
    private javax.swing.JButton bladerKnop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton openKnop;
    private javax.swing.JButton opslaanKnop;
    // End of variables declaration//GEN-END:variables
}
